version: '3.8'
services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
